### ISSUE TITLE
Избор на мониторинг

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2023#11]
Предишни години е бил използван

 * Nagios
 * Icinga
 * check_mk

За тази година ... Zabbix за да е по шарено :P

**Comment by miim-miiims** [comment]
За момента харесахме check_mk за monitoring.

Договорили сме се да следим следните параметри като bare minimum:
* при мрежата
  * ап-та - канали, трафик на wi-fi, брой клиенти
  * switch - портове, PoE бюджет
* при видео (бонус)
  * нива на звука

**Comment by zeridon** [comment]
@Yasen6275 беше конфил check_mk допълнително да се прегледат сетъпите за предишни годиини и да се окраде каквото може/харесва
