### ISSUE TITLE
Мониторинг на крайни потребители(устройства)

### ISSUE THREAD

**Issue by dexxter00** [OpenFest/openfest-network-2023#15]
Да се реши ще го има ли, морално ли е, както и законно ли е да събираме подобна информация?!

**Comment by zeridon** [comment]
Какво се има предвид с това?

**Comment by Yasen6275** [comment]
За мен клиентските устройства са лаптопи, телефони и подобни. Аз съм твърдо против.

**Comment by vhristev** [comment]
След дискусия няма да се мониторират крайните клиенти. Идеята е била да е за статистика.
