### ISSUE TITLE
SSH ключеве

### ISSUE THREAD

**Issue by dexxter00** [OpenFest/openfest-network-2023#16]
Да се съберат SSH ключовете на всички, които имат нужда от достъп.

**Comment by zeridon** [comment]
Инструмент за събиране от гитхъб: https://github.com/OpenFest/openfest-network-2019/tree/master/access

**Comment by zeridon** [comment]
Моля да добавите ключовете си (openssh формат) или в репото или като прикачени файлове

**Comment by zeridon** [comment]
ref https://github.com/OpenFest/openfest-network-2023/commit/e52b3134a32c64fd85cb9313f063c898abe49e20
