### ISSUE TITLE
WPA2-Enterprise

### ISSUE THREAD

**Issue by aastefanov** [OpenFest/openfest-network-2023#17]
Както говорихме на сбирката, добре е да проучим за минаването на Enterprise вместо PSK като криптиране.

**Comment by aastefanov** [comment]
Откъм конфигурацията на FreeRADIUS - това трябва да е достатъчно за да допусне всички: [https://serverfault.com/a/442470](https://serverfault.com/a/442470)
Можем да помислим да имаме реални потребители, които да минават в конкретен VLAN - дали за прод, дали за наши тестове.

Доколкото за сертификатите, с Let's Encrypt ще минем и клиентите ще им се доверяват по дефолт, стига да си направим нормално крипто конфигурациите.

По-трудното от минали години е че това включва конфигурацията на AP-тата да има IP и ключ/secret към сървъра.

**Comment by vhristev** [comment]
Това отпада ,заради iSO у-вата.
