### ISSUE TITLE
Автоматизация

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2023#18]
Да се опита напълно автоматизирано разпъване на всичко необходимо посредством ansible/cheff/puppet/salt/etc.

Ще е хубаво, но не е задължително.

**Comment by vhristev** [comment]
Какво означава разпъване може ли малко повече информация какво искате да автоматизирате аз мога да ви помогна с това.

**Comment by vhristev** [comment]
rosko
10:56 PM
Искахме да имаме автоматизация, която да провизира виртуалка с ОС и апликации с натискане на един бутон. Тази година сменяме концепцията и решихме да го оставим за следващата, понеже не знаем какво точно ще се прави.


Автоматизацита отпада за тази година.
