### ISSUE TITLE
Да се реши каква мрежова архитектура ще се използва

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2023#2]
- [ ] Преглед на архитектура от предишни години
 - [ ] Анализ
 - [ ] Избор на архитектура

Реалистично погледнато вариантите не са много, или поне не и тези които не искат огромно количество кабели.

**Comment by miim-miiims** [comment]
Oт първата среща:
* няма да променяме мрежовата архитектура
* switch-a на бариерата ще остане
  * @robotpanic(Килие) да покаже на @nemuikawa(Мими) как се setup-ва uplink-a за бариерата
* оставаме с IPACCT, ако има нещо Крокс ще говори с  тях
