### ISSUE TITLE
Адресно Планиране

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2023#5]
- [x] VLAN
 - [x] Мрежови обхвати за всеки VLAN
 - [x] Резервиране на адреси за твърди услуги/устройства

**Comment by miim-miiims** [comment]
Ще взимаме таблицата от миналата година.

**Comment by vhristev** [comment]
Ще се ползва това планиране: https://github.com/OpenFest/openfest-network-2023/blob/master/docs/ip-assignments.md

**Comment by aastefanov** [comment]
Резервациите ще видим в #9.
