### ISSUE TITLE
Интернет свързаност за събитието

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2023#7]
Да се уговори външна свързаност

 - [x] IPACCT
 - [ ] Резервна свързаност през TechPark (Veolia)
 - [x] Контакти за комуникация

**Comment by vhristev** [comment]
Уговорили сме среща на 17ти Окт.  с TechPark и A1.  

IPACCT ще потвърдят на 16ти Окт ,че има Uplink по трасето ( към бариера )
